In [45]:
import pandas as pd 
import numpy as np

## Import Dataset

In [48]:
df = pd.read_csv('../Datasets/credit_data.csv')
df.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [49]:
len(df)

2000

In [50]:
# total missing values
df.isnull().sum()

i#clientid    0
income        0
age           3
loan          0
c#default     0
dtype: int64

In [51]:
df = df.dropna()

In [52]:
df.isnull().sum()

i#clientid    0
income        0
age           0
loan          0
c#default     0
dtype: int64

### Define Inputs, Weights, Outputs
This is a binary classification problem 

In [53]:
# dont need client ID as input. Inputs = income, age, loan
inputs = df.iloc[:, 1:4].values
inputs

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [54]:
inputs.shape

(1997, 3)

In [58]:
# output = last column
outputs = df.iloc[:, 4].values
outputs

array([0, 0, 0, ..., 1, 0, 0])

In [56]:
outputs.shape

(1997,)

## Normalize Data: MinMaxScaler

In [34]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
inputs = scaler.fit_transform(inputs)
inputs

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [37]:
## Reshape the outputs to be our target column for our model
outputs = outputs.reshape(-1, 1)
outputs

array([[1.00000000e+00],
       [6.61559251e+04],
       [5.90170151e+01],
       [8.10653213e+03],
       [2.00000000e+00],
       [3.44151540e+04],
       [4.81171531e+01],
       [6.56474502e+03],
       [3.00000000e+00],
       [5.73171701e+04],
       [6.31080495e+01],
       [8.02095330e+03],
       [4.00000000e+00],
       [4.27095342e+04],
       [4.57519724e+01],
       [6.10364226e+03]])

## Implement Multi-layer Neural Network 

In [38]:
# determine how many layers in network 
(4 + 2) //  2 

3